Global dependencies has been removed because of build errors.
These settings should be defined in main application.

Example:
Compile error during compilation with javac.
\grails-app\utils\com\selly\util\pdfrenderer\PDFRendererUtil.java:6: error: package com.lowagie.text does not exist
import com.lowagie.text.DocumentException;
                       ^
		       D:\Documents\ServerDisc\selly\grails-app\utils\com\selly\util\pdfrenderer\PDFRendererUtil.java:13: error: cannot find symbol
		               public void renderDocument(String contents, OutputStream os) throws IOException, DocumentException {
			                                                                                                ^
															  symbol:   class DocumentException
															    location: class PDFRendererUtil
															    2 errors